import socket


def resolve_subdomain(domain: str, prefix: str) -> str:
    full: str = prefix + domain
    try:
        return socket.gethostbyname(full)
    except socket.gaierror:
        return "N/A"


def result_collection(domain: str, prefixes: set[str]) -> dict[str, str]:
    data: dict[str, str] = {}
    for prefix in prefixes:
        full: str = prefix + domain
        data[full] = resolve_subdomain(domain, prefix)
    return data


DOMAIN_PREFIXES = {
    "www.",
    "mail.",
    "ftp.",
    "localhost.",
    "webmail.",
    "smtp.",
    "pop.",
    "ns1.",
    "ns2.",
    "cpanel.",
    "autodiscover.",
    "autoconfig.",
    "imap.",
    "blog.",
    "dev.",
    "admin.",
    "forum.",
    "news.",
    "vpn.",
    "mysql.",
    "support.",
    "mobile.",
    "mx.",
    "static.",
    "docs.",
    "beta.",
    "shop.",
    "sql.",
    "secure.",
    "demo.",
    "wiki.",
    "web.",
    "media.",
    "email.",
    "images.",
    "img.",
    "intranet.",
    "portal.",
    "video.",
    "api.",
    "cdn.",
    "stats.",
    "dns.",
    "search.",
    "staging.",
    "server.",
    "chat.",
    "wap.",
    "my.",
    "svn.",
    "proxy.",
    "ads.",
    "host.",
    "crm.",
    "cms.",
    "backup.",
    "info.",
    "apps.",
    "download.",
    "remote.",
    "db.",
    "store.",
    "files.",
    "app.",
    "live.",
    "owa.",
    "start.",
    "sms.",
    "office.",
    "exchange.",
    "help.",
    "home.",
    "monitor.",
    "login.",
    "service.",
    "moodle.",
    "gateway.",
    "ssl.",
    "upload.",
    "online.",
    "survey.",
    "data.",
    "radio.",
    "extranet.",
    "jobs.",
    "services.",
    "panel.",
    "irc.",
    "cloud.",
    "git.",
    "members.",
    "preview.",
    "partner.",
    "vps.",
    "community.",
    "tools.",
    "projects.",
    "control.",
    "voip.",
    "gallery.",
    "billing.",
    "status.",
    "marketing.",
    "content.",
    "pay.",
    "access.",
    "sso.",
    "photos.",
    "auth.",
    "devel.",
    "master.",
    "qa.",
    "student.",
}
